### PR TITLE
fix: Travis builds

### PR DESCRIPTION
**Pull request by raszi**
Relates to #33

### CODE REVIEW

**Comment by raszi** [comment]
I don't really understand why Travis ran the tests with Ruby 1.9.3. 😮

**Comment by raszi** [comment]
I don't really understand why Travis ran the tests with Ruby 1.9.3 at all. 😮

**Comment by raszi** [comment]
According to [this](https://docs.travis-ci.com/user/customizing-the-build#Explicity-Including-Jobs) it should have not ran Ruby 1.9.3.

**Comment by raszi** [comment]
@weppos I guess I give up the fight with Travis here. 😞

**Comment by raszi** [comment]
Thanks to @BanzaiMan we have a working Travis config. 🎉

**Comment by raszi** [comment]
@weppos this is ready to go

**Comment by weppos** [comment]
I can't recall what was the issue, but Travis is now running successfully.
https://travis-ci.org/weppos/whois-parser/jobs/248302020

**Pull request closed without merging**
