### PR TITLE
Fix whois.nic.me parsing

### PR DESCRIPTION
**Pull request by raszi**

### CODE REVIEW

**Comment by raszi** [comment]
Any chance to approve this?

**Comment by weppos** [comment]
@raszi thanks for your PR. This PR contains a lot of changes outside the scope of the patch. For example, I can't understand the reason to change the travis build system and introduce more Gemfiles.

Can you please update your PR to ONLY change the parser section without touching any existing build system, changelog, gemfile or other files?

**Comment by raszi** [comment]
@weppos the reason why I needed to introduce the Travis changes and the new Gemfile is because the current Ruby version which is supported by Travis (Ruby 2.2) is not supported by `activesupport 5.0.0`, so my pull-request was failing.

I took the time to fix this issue by introducing a new Gemfile for the old Ruby versions which is supported by `activesupport < 5.0.0` and set up Travis to run the tests accordingly.

**Comment by raszi** [comment]
I also changed the way how the coverage is run to only consider the main supported Ruby version (which is I guess the Ruby 2.2) - of course this could be rolled back or I could create a separate PR for this.

**Comment by raszi** [comment]
And for the changelog, I thought that I'll spare some time for you and update the log file with the changes I made.

**Comment by weppos** [comment]
> @weppos the reason why I needed to introduce the Travis changes and the new Gemfile is because the current Ruby version which is supported by Travis (Ruby 2.2) is not supported by activesupport 5.0.0, so my pull-request was failing.

This is an interesting, fair point. I have been considering dropping AS dependency for years, I wonder if now it's the time to do it.

I have to think a little bit how I'd like to proceed in this sense. I'll make sure to come with at least a temporary solution that will allow to continue the development. However, I feel it should somehow be a separate PR, rather than being mixed to this one.

**Comment by raszi** [comment]
Well I can separate the `whois.nic.me` related changes into a separate PR from the Travis changes but does it change anything if you are going to merge that as well? :)

**Comment by raszi** [comment]
@weppos I created the separate pull-requests, it is your call what to do with them.

**Comment by njh** [comment]
Is it worth closing this in favour of #34 ?

**Comment by weppos** [comment]
Duplicate of #34

**Pull request closed without merging**
