### PR TITLE
Fixed .st response format and added support for `expires_on` property

### PR DESCRIPTION
**Pull request by fturmel**

### CODE REVIEW

**Comment by fturmel** [comment]
@weppos how likely are pull requests to get merged and released at this point? Not a whole lot of activity lately. thanks

**Comment by weppos** [comment]
@fturmel I'm sorry but as you can see from https://github.com/weppos/, my activity is still very intense and if any of my repo is experiencing some silence that generally means I have little time for open source contributions.

I do my best to follow up in a timely fashion, but I can't guarantee anything.

I'll hope to be able to review and merge as soon as possible.

**Comment by fturmel** [comment]
@weppos I understand you're busy and contributing a lot overall (and thank you for that). Just trying to assess at the moment whether I can realistically still use released gems for a project, use my own fork or just find another solution altogether.

**Comment by weppos** [comment]
Thanks for the patch!

**Pull request merged**
